/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class b2f_lib_B2FLib */

#ifndef _Included_b2f_lib_B2FLib
#define _Included_b2f_lib_B2FLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     b2f_lib_B2FLib
 * Method:    calc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_b2f_lib_B2FLib_calc(JNIEnv *, jclass, jint);
JNIEXPORT jobjectArray JNICALL Java_b2f_lib_B2FLib_render(JNIEnv *, jclass, jint width, jint height, jint depth);

#ifdef __cplusplus
}
#endif
#endif
